name: Module tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install environment
      run: sudo apt-get install -y bash libglfw3 libglfw3-dev xorg-dev libxkbcommon-dev meson clang git cmake libssl-dev cmake
    - name: Install libcurl
      run: sudo apt-get install --yes --no-install-recommends wget build-essential libcurl4
    - name: Wget curl
      run: wget https://curl.se/download/curl-7.81.0.tar.gz
    - name: Unpack curl
      run: tar -xvf curl-7.81.0.tar.gz
    - name: Install curl
      run: cd curl-7.81.0 && ./configure --with-openssl && make && sudo make install
    - name: Clone Dear ImGui
      run: sudo git clone --depth 1 --branch v1.88 https://github.com/ocornut/imgui.git /imgui
    - name: Clone ImPlot
      run: sudo git clone --depth 1 --branch v0.14 https://github.com/epezent/implot.git /implot
    - name: Configure project
      run: meson setup builddir --native-file=native.build
    - name: Build tests
      run: meson test -C builddir